name: Schedule

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  Print-Server-Date-Based-On-Schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Print out the Current Server Date every 2 minutes
        run: echo "The current Server Date is $(date)"
